### ISSUE TITLE
Changelog generation and deployed by Travis

### ISSUE THREAD

**Issue by EmmanuelDemey** [EmmanuelDemey/eslint-plugin-angular#8]

**Comment by albertosantini** [comment]
I have been using this script, as helper, to create the list of commits since last tag.

```
#!/bin/sh

git log --pretty=format:"* %s" --since="$(git show -s --format=%ad `git rev-list --tags --max-count=1`)"

```

Then I copy and paste the output in the changelog and edit it manually.
It is not the perfect workflow, but for a low commits project might be enough.

**Comment by remcohaszing** [comment]
I like the idea of sticking to the [AngularJS commit message conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y) and using `gulp-conventional-changelog` to generate the changelog.

A gulp task would look like this:

```js
gulp.task('changelog', function() {
  return gulp.src('CHANGELOG.md')
    .pipe(conventionalChangelog({
      preset: 'angular'
    }))
    .pipe(gulp.dest('.'));
});
```
